name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/git-rag-embedder
    permissions:
      id-token: write  # Required for trusted publishing:cite[3]:cite[6]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false:cite[6]
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build:cite[6]:cite[8]
      
      - name: Build package
        run: |
          python -m build:cite[6]:cite[8]
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1:cite[3]:cite[6]
